# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches:
    - main
  release:
    types:
    - created
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Publish VS Code Extension
        uses: HaaLeo/publish-vscode-extension@v1.6.2
            
